### ISSUE TITLE
'p' is not defined

### ISSUE THREAD

**Issue by gjuchault** [alpha123/Jaguar#2]
Care, in your function search, you use :

```
for (p = 0, len = parts[i].length; p < len;)
```

But p is not defined. You can fix it by adding p like that :

```
var parsed = Jaguar.parse(selector), i = 0, l = parsed.length, r = 0, len,
parts = [], results = [], hasDupe, removed = [], p;
```

**Comment by alpha123** [comment]
You're quite right. Thank you for spotting this.

I'm currently working on a newer, faster version of Jaguar based on AMD and with a complete test suite (which would have caught an oversight like this).
Since the current Jaguar -- which hasn't been truly updated for nearly a year -- is still as fast as current versions of Slick and Sizzle, Jaguar 2 will hopefully blow away all the competition. :)
